// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnssbbxobfahdmwyqqme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhuc3NiYnhvYmZhaGRtd3lxcW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzcyMjgsImV4cCI6MjA2MDY1MzIyOH0.drCPt6Cn7qDpBn4IOB1RcDI6pRzF6iWH4LDAyS70cpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);